### PR TITLE
Wolbachia

### PR DESCRIPTION
**Pull request by NavandarM**

### CODE REVIEW

**Comment by NavandarM** [comment]
New Taxa: Wolbachia and Pseudomonas Sp.

**Comment by NavandarM** [comment]
New Taxa: Wolbachia and Pseudomonas Sp.

**Comment by NavandarM** [comment]
New Taxa: Wolbachia and Pseudomonas Sp.

**Comment by WardDeb** [comment]
Do we need 4 extra pseudomonas and 3 extra wolbachia species ? Isn't just one of each enough ?

**Comment by NavandarM** [comment]
Yes, I thought of selecting one of the species from these sets. But below is the detailed scenario of the test.

**Regarding Wolbachia,**

This concern project 3195 (Iovino lab), Here we observed the maximum hits for Taxa id: 953 (Wolbachia [genus]) for each sample.
statistics of hits:
Numer of hits Taxa id (Sample)
1624256 953  (Sample1)
1175760 953  (Sample2)
1896715 953  (Sample3)
1607378 953  (Sample4)
2913096 953  (Sample5)
138687  305  (Sample6)
2468677 953  (Sample7)
3178043 953  (Sample8)
2337444 953  (Sample9)

_953 Taxa id belongs to Wolbachia [genus level]_

However, at species level we few hits:
Number_of_hits Taxa_id 
10416   80849 ( Wolbachia endosymbiont strain TRS of Brugia malayi)
11534   80849 ( Wolbachia endosymbiont strain TRS of Brugia malayi)
14041   1633785 (Wolbachia endosymbiont of Drosophila incompta)
12207   1633785 (Wolbachia endosymbiont of Drosophila incompta)
15856   1633785 (Wolbachia endosymbiont of Drosophila incompta)
11693   1633785 (Wolbachia endosymbiont of Drosophila incompta)
12856   246273 (Wolbachia endosymbiont of Cimex lectularius)
10982   246273 (Wolbachia endosymbiont of Cimex lectularius)
14002   246273 (Wolbachia endosymbiont of Cimex lectularius)
10273   246273 (Wolbachia endosymbiont of Cimex lectularius)

Hence, decided to consider these three different species of Wolbachia.
____________________________________________________________

**Regarding Pseudomans species:**
(This concerns two different projects, #3199 and #3219 )

_From Project 3199 (Akhtar lab)_
In the samples (total samples = 2) collectively we got following hits
 
Number_of_hits Taxa_id
777666  1827300 (Pseudomonas sp. MYb193)
2477174  1827300 (Pseudomonas sp. MYb193)
1012531 286 (Pseudomonas [genus level taxaid])
315733  286 (Pseudomonas [genus level taxaid])

Hence, Pseudomonas sp. MYb193 was considered.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - 

_From Project 3219 (Iovino lab):_

In the samples (total samples = 3) collectively we got following hits
Number_of_hits Taxa_id
50497   1415630 (Pseudomonas sp. TKP)
32641   1415630 (Pseudomonas sp. TKP)
18757   2126069 (Pseudomonas sp. LBUM920)
17022   2126069 (Pseudomonas sp. LBUM920)
27686   219572 (Pseudomonas antarctica)
24884   219572 (Pseudomonas antarctica)
216913  286 (Pseudomnas [genus level])
164315  286 (Pseudomnas [genus level])

Hence, because of low number of hits, respective three species were selected.)

What would be your recommendation in such case?

**Comment by WardDeb** [comment]
cfr. https://github.com/maxplanck-ie/dissectBCL/pull/201
Let's revisit pseudomonas specifically later.

**Pull request closed without merging**
